version: '3'
services:
  apache-php-phpmailer5.2:
    image: takeshitawork/web-server-php:apache-php5.6
    ports:
      - 10080:80
      - 10443:443
    volumes:
      - "../src/PHPMailer5.2:/var/www"

  apache-php-phpmailer6.9:
    image: takeshitawork/web-server-php:apache-php8.3
    ports:
      - 20080:80
      - 20443:443
    volumes:
      - "../src/PHPMailer6.9:/var/www"
  smtp:
    image: takeshitawork/web-server-php:mailcatcher
    ports:
    - "1080:1080"
